### ISSUE TITLE
Test Mattermost support

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-plugin-slack#1]
Mattermost uses a very similar (If not the exact same) message payload format as Slack.  Test if notifications will work in Mattermost servers as well.

Note: I can test once the plugin hits the catalog and is installable

**Comment by mcarlton00** [comment]
Doesn't appear to work in Mattermost servers.  It looks like the user_id field isn't being populated correctly.
Example entry from the Mattermost logs:
```
"msg":"Unable to parse incoming data","path":"/hooks/d5n6uqnyaffy9rrsatr9c1sj7o","request_id":"qn5ohty1ipdhpeocyob18ob76c","ip_addr":"50.90.196.168","user_id":"","method":"POST","err_where":"IncomingWebhookRequestFromJson","http_code":400,"err_details":"EOF"}
```

**Comment by dannyhanes** [comment]
+1 for Mattermost support.

**Comment by anthonylavado** [comment]
PR #5 should fix this. Let me cut a release.

**Comment by mcarlton00** [comment]
This is working in the current nightly releases.
